import { useEffect, useState } from 'react'
import { ArrowRight, Clock3, MapPin, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { apiFetch } from '@/lib/api'

const fallback = { title: 'Ilorin in History', content: 'A short journey through the people, institutions, and shared responsibility that continue to shape the Ilorin Emirate community.', metadata: { eyebrow: 'A living heritage', intro: 'From a community rooted in culture and harmony to a youth-led network working across five Local Government Areas, this is a concise IEYDA timeline.', stats: [{ label: 'IEYDA incorporated', value: '2014' }, { label: 'LGAs united', value: '5' }, { label: 'Member associations', value: '200+' }], timeline: [] } }

export default function IlorinHistoryPage() {
  const [page, setPage] = useState(() => window.__BOOTSTRAP_DATA__?.history || fallback)
  useEffect(() => { apiFetch('/history/ilorin').then((value) => { const data = value?.data || value; if (data) setPage(data) }).catch(() => {}) }, [])
  const meta = page.metadata || fallback.metadata
  return <div className="pt-20 min-h-screen bg-[#071b17] text-white">
    <section className="relative overflow-hidden px-6 py-24 md:py-32"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(circle at 20% 20%, #d4af37 0, transparent 30%), radial-gradient(circle at 80% 50%, #147d5a 0, transparent 35%)' }} /><div className="container-max relative z-10"><p className="mb-5 text-sm font-bold uppercase tracking-[0.3em] text-[#e2bd53]">{meta.eyebrow || 'A living heritage'}</p><h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-7xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/70">{meta.intro || page.content}</p><div className="mt-12 grid max-w-3xl gap-4 sm:grid-cols-3">{(meta.stats || []).map((stat) => <div key={stat.label} className="rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur"><div className="text-3xl font-bold text-[#e2bd53]">{stat.value}</div><div className="mt-2 text-sm text-white/60">{stat.label}</div></div>)}</div></div></section>
    <section className="relative border-t border-white/10 px-6 py-20"><div className="container-max"><div className="mb-14 flex items-center gap-3 text-[#e2bd53]"><Clock3 className="h-5 w-5" /><span className="text-sm font-bold uppercase tracking-[0.25em]">The journey continues</span></div><div className="relative ml-3 border-l border-[#e2bd53]/40 pl-8 md:ml-12 md:pl-16">{(meta.timeline || []).map((item, index) => <motion.article key={`${item.year}-${item.title}`} initial={{ opacity: 0, x: 24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className="relative mb-16 max-w-3xl"><span className="absolute -left-[2.65rem] top-1 h-4 w-4 rounded-full border-4 border-[#071b17] bg-[#e2bd53] md:-left-[4.45rem]" /><div className="mb-3 text-sm font-bold tracking-[0.2em] text-[#e2bd53]">{item.year}</div><h2 className="text-2xl font-bold md:text-4xl">{item.title}</h2><p className="mt-4 text-base leading-relaxed text-white/65 md:text-lg">{item.description}</p></motion.article>)}</div><div className="mt-8"><Link to="/" className="inline-flex items-center gap-2 rounded-full border border-[#e2bd53]/50 px-5 py-3 text-sm font-bold text-[#e2bd53] transition hover:bg-[#e2bd53] hover:text-[#071b17]">Back to IEYDA <ArrowRight className="h-4 w-4" /></Link></div></div></section><div className="pointer-events-none fixed bottom-8 right-8 hidden text-[#e2bd53]/30 md:block"><MapPin className="h-16 w-16" /></div><Sparkles className="pointer-events-none absolute right-10 top-40 h-8 w-8 text-[#e2bd53]/40" />
  </div>
}
